### ISSUE TITLE
form enctype="multipart/form-data" caused NPE.

### ISSUE THREAD

**Issue by CrossLee** [actframework/actframework#1360] opened 2020-08-21 01:56 UTC
html code:

```html
<form name="test" action="/test" method="post" enctype="multipart/form-data">
<input type="text" name="user[name]" />
<input type="submit" value="submit">
</form>
```

Upon clicking submit button, Act will throw out an NPE.

**Comment by greenlaw110** [comment] 2020-08-21 02:56
@CrossLee can you please add the controller source code as well?

**Comment by CrossLee** [comment] 2020-08-21 06:14
@GetAction("/test")
public void test(User user){
// ...
}

**Comment by greenlaw110** [comment] 2020-12-26 23:48
@CrossLee is this one duplicate of #1369 ?

**Comment by greenlaw110** [comment] 2020-12-26 23:54
I am pretty sure #1369 is a duplicate of this one, which has been fixed already. So will close this issue

**Closed by greenlaw110** 2020-12-26 23:54 UTC
