### ISSUE TITLE
qrcode method problem

### ISSUE THREAD

**Issue by xbird** [actframework/actframework#127] opened 2017-03-29 08:57 UTC
when i follow this http://www.tudou.com/programs/view/8KTZDHNkMl0 ,
the page is always on loading  when i use  qrcode&barcode  method to make images .

**Comment by greenlaw110** [comment] 2017-03-31 02:42
The root cause is #130

**Comment by greenlaw110** [comment] 2017-04-03 01:52
Fixed in 1.0.7

**Closed by greenlaw110** 2017-04-03 01:52 UTC
