### ISSUE TITLE
fonts can't load when app restart

### ISSUE THREAD

**Issue by 18807600203** [actframework/actframework#176] opened 2017-04-28 16:32 UTC
The first boot app is normal.However, after I modified the code, APP automatically restart again after the visit, fonts failed to load, resulting in the font and icon on the page unusual

i used actFramework 1.2.0 ,rythm ,vue 2.2.6 and iview2.0.0
console has some warning:
`Failed to decode downloaded font: http://127.0.0.1:8080/asset/css/fonts/ionicons.ttf?v=2.0.0
OTS parsing error: FFTM: misaligned table
Failed to decode downloaded font: http://127.0.0.1:8080/asset/css/fonts/ionicons.woff?v=2.0.0
OTS parsing error: incorrect file size in WOFF header`

**Comment by greenlaw110** [comment] 2017-04-28 20:10
@18807600203 thanks for issue reporting. Are you able to provide a simple project to reproduce this issue? that would help a lot

**Comment by 18807600203** [comment] 2017-04-29 01:43
[https://github.com/18807600203/t1.git](url)
 this is a  simple project. And I  test my  project  today , 
run app in windows 10 64bit , eclipse 4.5.2 64bit , just the above problem. but when use windows7 32bit 
eclipse 4.5.2 32bit , the first launch will not be able to load the situation.
I was a migration project from spring boot 1.5.3, but not in that environment

**Comment by greenlaw110** [comment] 2017-04-29 03:08
So you mean ActFramework cannot work with 32bit JVM? Can you raise in a different issue?

**Comment by 18807600203** [comment] 2017-04-29 03:13
Temporary solution, excluded font files from filtering by adding this XML in the <configuration> section for maven-resources-plugin. 
But in spring boot project, this configuration does not require
```
<plugins>
...
  <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-resources-plugin</artifactId>
    <version>3.0.2</version>
    <configuration>
      <nonFilteredFileExtensions>					  
        <nonFilteredFileExtension>eot</nonFilteredFileExtension>				                
        <nonFilteredFileExtension>svg</nonFilteredFileExtension>				
        <nonFilteredFileExtension>ttf</nonFilteredFileExtension>				
        <nonFilteredFileExtension>woff</nonFilteredFileExtension>				
        <nonFilteredFileExtension>woff2</nonFilteredFileExtension>
      </nonFilteredFileExtensions>
    </configuration>
  </plugin>
</plugins>
```

**Comment by 18807600203** [comment] 2017-04-29 04:05
i am not sure  ActFramework cannot work with 32bit JVM.I use it in my two different environment, the app run normal,but view different. just my project
32bit jvm 
<strong>A�?</strong>
64bit jvm
<strong>A门</strong>

it was vuejs output param to html ,is ActFramework or rythm bug ?

**Comment by greenlaw110** [comment] 2017-04-29 05:57
Well it's really encoding issue. Both Act and Rythm use UTF-8. Are you using the same browser and get different result? What does the html source look like?

**Comment by greenlaw110** [comment] 2017-04-29 05:58
@18807600203 Can I read your `pom.xml` file?

**Comment by 18807600203** [comment] 2017-04-29 07:54
two different environment  using the same browser ,Chrome 58.0.3029.81
html source   `<strong>A�?</strong>` , and i find it only part of the text is like this
![2](https://cloud.githubusercontent.com/assets/14899361/25553947/ac7dd182-2cf3-11e7-9651-57de0bfdb8bd.jpg)
![1](https://cloud.githubusercontent.com/assets/14899361/25553949/ac82f7c0-2cf3-11e7-9ede-5cfe6c5359da.jpg)

when i click left sider to show a view, the html sources look like this , Similar to error page
![3](https://cloud.githubusercontent.com/assets/14899361/25553948/ac7f5232-2cf3-11e7-96fc-a001933443d2.jpg)

**Comment by greenlaw110** [comment] 2017-05-02 01:18
@18807600203 I think this is a different issue. Not relevant to the fonts loading problem which is really caused by the resource plugin in your pom file. Can you please close this issue and submit an new one with clear description on the encoding problem?

**Closed** 2017-05-02 01:22 UTC
Labels: bug, help wanted
